-- Plan v4: the doctor's ramp (19 Aug 2026 review). Rebuild from 20 km/week
-- at +15% per week to a 50 km peak held W9-W10, then ramp down to race day.
-- v3 rows are kept as history; the export views move to v4. The week 2
-- 'reduce' decision is re-tagged v4 (it is v4's founding decision).
-- Generated by scripts/gen_v4_migration.py — edit that script, not this file.

delete from plan_session where plan_version = 'v4';
delete from plan_week    where plan_version = 'v4';

insert into plan_week (plan_version, week_no, phase, week_start, target_km, long_run_km, sessions_planned, is_cutback, note) values
  ('v4', 1, 'Stabilize', '2026-08-10', 31, 12.4, 3, false, 'Adopted retroactively: run 10–16 Aug under the starting plan’s grid, before the v3 document existed. Sessions recorded as run, not as planned.'),
  ('v4', 2, 'Stabilize', '2026-08-17', 20, 12, 3, false, 'Doctor-advised reduce week (20–30 km band): daily stretching protocol begins; hip/core/calf/knee strength; flat routes, slopes walked. First half recorded as run.'),
  ('v4', 3, 'Build', '2026-08-24', 23, 12, 4, false, 'The 15% ramp begins. Fuel practice on runs >75 min (30–40 g/h). Daily stretching; flat routes.'),
  ('v4', 4, 'Build', '2026-08-31', 26, 13, 4, false, 'Long run is the sole progression lever.'),
  ('v4', 5, 'Build', '2026-09-07', 30, 15, 4, false, 'Hold form; strength continues; review the heel trend before progressing.'),
  ('v4', 6, 'Build', '2026-09-14', 35, 17, 4, false, 'Fuel/fluid/equipment rehearsal; sweat-rate test.'),
  ('v4', 7, 'Build', '2026-09-21', 40, 20, 5, false, 'Midweek medium-long run begins — spreads load.'),
  ('v4', 8, 'Build', '2026-09-28', 46, 23, 5, false, 'Log GI, skin, foot, late mechanics. Fuel ≥45 g/h on the long run.'),
  ('v4', 9, 'Peak', '2026-10-05', 50, 26, 5, false, 'Peak week 1. The fueled ≥26 km long run — the minimum viable peak — lands here under v4.'),
  ('v4', 10, 'Peak', '2026-10-12', 50, 27, 5, false, 'Peak week 2. Fuel ≥60 g/h; settle race gear.'),
  ('v4', 11, 'Tune-up', '2026-10-19', 43, 21.1, 5, false, 'Half-marathon tune-up at controlled effort. Race-morning rehearsal; result sets the marathon pacing plan.'),
  ('v4', 12, 'Descend', '2026-10-26', 38, 18, 5, false, 'Descent begins. 2×3 km at marathon effort inside the long run; fuel ≥60 g/h.'),
  ('v4', 13, 'Descend', '2026-11-02', 33, 16, 5, false, 'Go/no-go: choose time goal / completion / run-walk from evidence.'),
  ('v4', 14, 'Descend', '2026-11-09', 28, 14, 5, false, 'Dress rehearsal at reduced volume: race breakfast, kit, anti-chafe, race start time; 4–6 km continuous at marathon effort; fuel ≥60 g/h.'),
  ('v4', 15, 'Taper', '2026-11-16', 24, 12, 4, false, 'Confirm race plan; strength maintenance; nothing new.'),
  ('v4', 16, 'Taper', '2026-11-23', 20, 10, 4, false, 'Volume down, small doses of marathon effort; protect sleep.'),
  ('v4', 17, 'Race week', '2026-11-30', 15, null, 3, false, 'Freshness and logistics. Carb load Wed–Thu 10–12 g/kg/day. Race Fri 4 Dec.');

insert into plan_session (plan_version, session_date, session_type, title, target_km, time_cap_min, detail, fuel_target_g_h, is_key, milestone) values
  ('v4', '2026-08-12', 'easy', 'Easy run (as run)', 8.9, null, 'Adopted retroactively: run 10–16 Aug under the starting plan’s grid, before the v3 document existed. Sessions recorded as run, not as planned.', null, false, null),
  ('v4', '2026-08-13', 'easy', 'Easy run (as run)', 9.5, null, 'Adopted retroactively: run 10–16 Aug under the starting plan’s grid, before the v3 document existed. Sessions recorded as run, not as planned.', null, false, null),
  ('v4', '2026-08-16', 'long', 'Long run (as run)', 12.4, null, 'Adopted retroactively: run 10–16 Aug under the starting plan’s grid, before the v3 document existed. Sessions recorded as run, not as planned.', null, true, null),
  ('v4', '2026-08-17', 'easy', 'Easy run (as run)', 9.4, null, 'Run before the v4 revision existed.', null, false, null),
  ('v4', '2026-08-19', 'easy', 'Easy run (as run)', 12, null, 'Run the morning of the doctor review; heel 3/10 at run start.', null, false, null),
  ('v4', '2026-08-20', 'rest', 'Rest + daily stretching protocol', null, null, 'Towel stretch, toe extension, calf on step, calf against wall — every day from here.', null, false, null),
  ('v4', '2026-08-21', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-08-22', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-08-23', 'rest', 'Rest / mobility', null, null, null, null, false, null),
  ('v4', '2026-08-24', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-08-25', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-08-25', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-08-26', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-08-27', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-08-28', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-08-28', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-08-29', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-08-30', 'long', 'Long run 12 km (cap 1:30)', 12, 90, null, 30, true, null),
  ('v4', '2026-08-31', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-09-01', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-09-01', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-09-02', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-09-03', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-09-04', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-09-04', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-09-05', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-09-06', 'long', 'Long run 13 km (cap 1:40)', 13, 100, null, 35, true, null),
  ('v4', '2026-09-07', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-09-08', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-09-08', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-09-09', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-09-10', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-09-11', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-09-11', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-09-12', 'shakeout', 'Short easy 4 km, flat', 4, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-09-13', 'long', 'Long run 15 km (cap 1:55)', 15, 115, null, 35, true, 'Farthest-ever long run'),
  ('v4', '2026-09-14', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-09-15', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-09-15', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-09-16', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-09-17', 'easy', 'Easy 7 km, flat', 7, null, null, null, false, null),
  ('v4', '2026-09-18', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-09-18', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-09-19', 'shakeout', 'Short easy 4 km, flat', 4, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-09-20', 'long', 'Long run 17 km (cap 2:10)', 17, 130, 'Fuel/fluid/equipment rehearsal; sweat-rate test.', 40, true, 'Farthest-ever long run'),
  ('v4', '2026-09-21', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-09-22', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-09-22', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-09-23', 'mlr', 'Medium-long run 10 km', 10, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, false, null),
  ('v4', '2026-09-24', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-09-25', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-09-25', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-09-26', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-09-27', 'long', 'Long run 20 km (cap 2:30)', 20, 150, null, 45, true, 'Farthest-ever long run'),
  ('v4', '2026-09-28', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-09-29', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-09-29', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-09-30', 'mlr', 'Medium-long run 11 km', 11, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, false, null),
  ('v4', '2026-10-01', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-10-02', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-10-02', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-10-03', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-10-04', 'long', 'Long run 23 km (cap 2:50)', 23, 170, 'Log GI, skin, foot, late mechanics. Fuel ≥45 g/h on the long run.', 45, true, 'Farthest-ever long run'),
  ('v4', '2026-10-05', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-10-06', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-10-06', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-10-07', 'mlr', 'Medium-long run 12 km', 12, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-10-08', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-10-09', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-10-09', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-10-10', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-10-11', 'long', 'Long run 26 km (cap 3:15)', 26, 195, 'Peak week 1. The fueled ≥26 km long run — the minimum viable peak — lands here under v4.', 55, true, 'Minimum viable peak — fueled ≥26 km'),
  ('v4', '2026-10-12', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-10-13', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-10-13', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-10-14', 'mlr', 'Medium-long run 12 km', 12, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-10-15', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-10-16', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-10-16', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-10-17', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-10-18', 'long', 'Long run 27 km (cap 3:20)', 27, 200, 'Peak week 2. Fuel ≥60 g/h; settle race gear.', 60, true, 'Farthest-ever long run'),
  ('v4', '2026-10-19', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-10-20', 'easy', 'Easy 6 km, flat', 6, null, null, null, false, null),
  ('v4', '2026-10-20', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-10-21', 'mlr', 'Medium-long run 11 km', 11, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-10-22', 'easy', 'Rest or 20 min easy jog (pre-race)', null, null, 'Freshness for the Sunday half; no quality this week.', null, false, null),
  ('v4', '2026-10-23', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-10-23', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-10-24', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-10-25', 'race', 'Half-marathon tune-up — controlled effort', 21.1, null, 'Not all-out. Race-morning rehearsal: breakfast, kit, fuel under race stress. If amber: run as a controlled long run instead.', 50, true, 'Half-marathon tune-up race'),
  ('v4', '2026-10-26', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-10-27', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-10-27', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-10-28', 'mlr', 'Medium-long run 10 km', 10, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-10-29', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-10-30', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-10-30', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-10-31', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-11-01', 'long', 'Long run 18 km (cap 2:15)', 18, 135, 'Descent begins. 2×3 km at marathon effort inside the long run; fuel ≥60 g/h. Includes 2×3 km at marathon effort.', 60, true, null),
  ('v4', '2026-11-02', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-11-03', 'easy', 'Easy 5 km, flat', 5, null, null, null, false, null),
  ('v4', '2026-11-03', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-11-04', 'mlr', 'Medium-long run 8 km', 8, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-11-05', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-11-06', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-11-06', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-11-07', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-11-08', 'long', 'Long run 16 km (cap 2:00)', 16, 120, null, 60, true, null),
  ('v4', '2026-11-08', 'review', 'Go/no-go review', null, null, 'Formal decision from evidence: time goal / completion / run-walk / defer. Recorded in the weekly decision log.', null, true, 'Week 13 go/no-go decision'),
  ('v4', '2026-11-09', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-11-10', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-11-10', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-11-11', 'mlr', 'Medium-long run 6 km', 6, null, 'Load-spreading, not load-adding; first run shortened when reducing.', null, true, null),
  ('v4', '2026-11-12', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-11-13', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-11-13', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-11-14', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-11-15', 'long', 'Long run 14 km (cap 1:45)', 14, 105, 'Dress rehearsal at reduced volume: race breakfast, kit, anti-chafe, race start time; 4–6 km continuous at marathon effort; fuel ≥60 g/h. Includes 4–6 km continuous at marathon effort.', 60, true, 'Dress rehearsal — the confidence anchor'),
  ('v4', '2026-11-16', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-11-17', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-11-17', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-11-18', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-11-19', 'quality', '2×2 km at marathon effort', 6, null, 'Small race-specific dose; skip on any amber.', null, false, null),
  ('v4', '2026-11-20', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-11-20', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-11-21', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-11-22', 'long', 'Long run 12 km (cap 1:30)', 12, 90, null, 60, true, null),
  ('v4', '2026-11-23', 'rest', 'Rest / mobility', null, null, 'Post-long-run assessment day; daily stretching.', null, false, null),
  ('v4', '2026-11-24', 'easy', 'Easy 4 km, flat', 4, null, null, null, false, null),
  ('v4', '2026-11-24', 'strength', 'Strength A', null, null, 'Hip and core focus (doctor''s priority). 2–4 sets, 2–3 reps in reserve; no failure.', null, false, null),
  ('v4', '2026-11-25', 'rest', 'Rest or short easy 4 km, flat', null, null, null, null, false, null),
  ('v4', '2026-11-26', 'quality', '3×2 km at marathon effort', 6, null, 'Small race-specific dose; skip on any amber.', null, false, null),
  ('v4', '2026-11-27', 'rest', 'Rest', null, null, null, null, false, null),
  ('v4', '2026-11-27', 'strength', 'Strength B', null, null, 'Calf and knee focus — drop heel raises (doctor: specifically a loading stretch). No upper body. Load-bearing for this plan — absence is recorded, not waved through.', null, false, null),
  ('v4', '2026-11-28', 'shakeout', 'Short easy 3 km, flat', 3, null, 'No fatigue accumulation before the long run. No strides.', null, false, null),
  ('v4', '2026-11-29', 'long', 'Long run 10 km (cap 1:15)', 10, 75, null, 60, true, null),
  ('v4', '2026-11-30', 'rest', 'Rest / mobility', null, null, null, null, false, null),
  ('v4', '2026-12-01', 'easy', 'Easy 20–25 min', 4, null, null, null, false, null),
  ('v4', '2026-12-02', 'quality', '2×1.5 km at marathon effort', 6, 40, 'Carb load begins today: 10–12 g/kg/day Wed–Thu.', null, false, null),
  ('v4', '2026-12-03', 'rest', 'Rest (carb load continues)', null, null, 'Race kit laid out; early night.', null, false, null),
  ('v4', '2026-12-04', 'race', 'BYD Singapore Marathon', 42.2, null, 'Segments: 0–10 settle · 10–25 rhythm · 25–35 work · 35–42 execute. Fuel ≥60 g/h from 20–30 min. Red flag overrides participation.', 60, true, 'Race day'),
  ('v4', '2026-12-05', 'rest', 'Recovery walk only', null, null, null, null, false, null),
  ('v4', '2026-12-06', 'rest', 'Recovery walk only', null, null, null, null, false, null),
  ('v4', '2026-12-01', 'strength', 'Strength — light activation', null, null, 'Familiar light work only; last session before race.', null, false, null);

update weekly_decision set plan_version = 'v4' where plan_version = 'v3' and week_no = 2;

create or replace view export_weekly_progress as
select
  p.week_no,
  p.phase,
  p.week_start,
  p.target_km,
  p.long_run_km,
  p.sessions_planned,
  p.is_cutback,
  coalesce(sum(r.distance_km), 0)          as actual_km,
  count(r.garmin_activity_id)::integer     as sessions_logged,
  max(r.distance_km)                       as longest_run_km
from plan_week p
left join export_runs r
  on r.run_date >= p.week_start and r.run_date < p.week_start + 7
where p.plan_version = 'v4'
group by p.week_no, p.phase, p.week_start, p.target_km, p.long_run_km,
         p.sessions_planned, p.is_cutback
order by p.week_no;

create or replace view export_plan_sessions as
select session_date, session_type, title, target_km, time_cap_min, detail,
       fuel_target_g_h, is_key, milestone
from plan_session
where plan_version = 'v4';

create or replace view export_weekly_decisions as
select week_no, decided_on, decision, lever, rationale, what_went_right,
       data_confidence
from weekly_decision
where plan_version = 'v4' and is_public;

create or replace view export_weekly_load as
select
  p.week_no,
  p.week_start,
  p.target_km,
  p.long_run_km                                   as target_long_km,
  p.is_cutback,
  coalesce(sum(r.distance_km), 0)                 as actual_km,
  round(coalesce(sum(r.duration_s), 0) / 60.0)    as run_minutes,
  round(coalesce(max(r.duration_s), 0) / 60.0)    as longest_run_minutes,
  max(r.distance_km)                              as longest_run_km,
  case when sum(r.distance_km) > 0
       then round(max(r.distance_km) / sum(r.distance_km) * 100)
  end                                             as long_run_share_pct,
  (select round(sum(l.session_load))
     from v_session_load l
    where l.day >= p.week_start and l.day < p.week_start + 7) as session_load,
  (select count(*)
     from v_daily_status s
    where s.day >= p.week_start and s.day < p.week_start + 7
      and s.status like 'amber%')                 as amber_days
from plan_week p
left join export_runs r
  on r.run_date >= p.week_start and r.run_date < p.week_start + 7
where p.plan_version = 'v4'
group by p.week_no, p.week_start, p.target_km, p.long_run_km, p.is_cutback
order by p.week_no;

revoke all on export_weekly_progress, export_plan_sessions,
              export_weekly_decisions, export_weekly_load
  from anon, authenticated;
